//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System.CodeDom.Compiler;
using System.ComponentModel;
using System.Diagnostics;
using System.Diagnostics.CodeAnalysis;
using System.Globalization;
using System.Resources;
using System.Runtime.CompilerServices;

namespace MassFileRenamer.GUI.Properties {
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [GeneratedCode("System.Resources.Tools.StronglyTypedResourceBuilder", "16.0.0.0")]
    [DebuggerNonUserCode()]
    [CompilerGenerated()]
    internal class Resources {
        
        private static ResourceManager resourceMan;
        
        private static CultureInfo resourceCulture;
        
        [SuppressMessage("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [EditorBrowsable(EditorBrowsableState.Advanced)]
        internal static ResourceManager ResourceManager {
            get {
                if (ReferenceEquals(resourceMan, null)) {
                    ResourceManager temp = new ResourceManager("MassFileRenamer.GUI.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [EditorBrowsable(EditorBrowsableState.Advanced)]
        internal static CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ready.
        /// </summary>
        internal static string AppIdle {
            get {
                return ResourceManager.GetString("AppIdle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to config.json.
        /// </summary>
        internal static string ConfigFilename {
            get {
                return ResourceManager.GetString("ConfigFilename", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Could not find the configuration file..
        /// </summary>
        internal static string Error_ConfigFileNotFound {
            get {
                return ResourceManager.GetString("Error_ConfigFileNotFound", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The text to be found cannot be blank.
        ///
        ///Type the text you want replaced, and then try again..
        /// </summary>
        internal static string Error_FindWhatRequired {
            get {
                return ResourceManager.GetString("Error_FindWhatRequired", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The text to use as replacement text cannot be blank.
        ///
        ///Type a value for this text, and then try again..
        /// </summary>
        internal static string Error_ReplaceWithBlank {
            get {
                return ResourceManager.GetString("Error_ReplaceWithBlank", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Could not locate the folder &apos;{0}&apos; on the disk.
        ///
        ///Please specify a folder path of click the &apos;...&apos; button to browse for one..
        /// </summary>
        internal static string Error_RootDirectoryNotFound {
            get {
                return ResourceManager.GetString("Error_RootDirectoryNotFound", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Folders|.
        /// </summary>
        internal static string FolderSelectDialogFIlters {
            get {
                return ResourceManager.GetString("FolderSelectDialogFIlters", resourceCulture);
            }
        }
    }
}
