//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MFR.GUI.Windows.Properties {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "16.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("MFR.GUI.Windows.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ready.
        /// </summary>
        public static string AppIdle {
            get {
                return ResourceManager.GetString("AppIdle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Project File Renamer has detected that subFolder(s) or C# project(s) exist in directory tree of the Starting Folder who would be overwritten by your proposed change(s).
        ///
        ///Such an operation could be very destructive of many hours or days of previous work.
        ///
        ///Do you still wish to continue?.
        /// </summary>
        public static string Confirm_ReplaceTextThatWouldOverwriteExistingFiles {
            get {
                return ResourceManager.GetString("Confirm_ReplaceTextThatWouldOverwriteExistingFiles", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to *** ERROR *** The folder &apos;{0}&apos; (currently-configured starting folder) does  not exist.  Therefore, we cannot set up the auto-completion of the Find What combo box using its subfolders that contain projects..
        /// </summary>
        public static string Error_CantSetUpFindWhatComboStartFolderNotExists {
            get {
                return ResourceManager.GetString("Error_CantSetUpFindWhatComboStartFolderNotExists", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please provide a value for the text to be located during the search..
        /// </summary>
        public static string Error_FindWhat_MissingValue {
            get {
                return ResourceManager.GetString("Error_FindWhat_MissingValue", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please type different values in the Text to Be Replaced and With What fields..
        /// </summary>
        public static string Error_FindWhat_ReplaceWith_Identical {
            get {
                return ResourceManager.GetString("Error_FindWhat_ReplaceWith_Identical", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please select at least one operation on the Operations tab.
        ///NOTE: To show the Operations tab (if it isn&apos;t already visible), click the More button.
        ///
        ///Would you like to select all operations now, and try again?.
        /// </summary>
        public static string Error_NoOperationSelected {
            get {
                return ResourceManager.GetString("Error_NoOperationSelected", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please provide a value for the replacement value to be used during the search..
        /// </summary>
        public static string Error_Specify_ReplaceWith {
            get {
                return ResourceManager.GetString("Error_Specify_ReplaceWith", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please select a directory that contains a Visual Studio Solution (*.sln) file for the What Folder Should the Operation Start In field.
        ///
        ///Do you want to proceed regardless?  CAUTION: Unpredictable things may happen.  Don&apos;t say we did not warn you..
        /// </summary>
        public static string Error_StartingFolderMustContainSolutionFile {
            get {
                return ResourceManager.GetString("Error_StartingFolderMustContainSolutionFile", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Getting ready to start the operations....
        /// </summary>
        public static string Info_PreparingStartOperations {
            get {
                return ResourceManager.GetString("Info_PreparingStartOperations", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        public static System.Drawing.Bitmap SwitchUpDown_16x {
            get {
                object obj = ResourceManager.GetObject("SwitchUpDown_16x", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
    }
}