//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MFR.CommandLine.Validators.Constants.Properties {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "16.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("MFR.CommandLine.Validators.Constants.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The command-line arguments could not be parsed..
        /// </summary>
        public static string CommandLineInfoIsNull {
            get {
                return ResourceManager.GetString("CommandLineInfoIsNull", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The &apos;Find What&apos; value is blank, or it contains only whitespace..
        /// </summary>
        public static string FindWhatBlank {
            get {
                return ResourceManager.GetString("FindWhatBlank", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The specified starting directory, &apos;{0}&apos;, exists on disk but does not contain a Visual Studio Solution (*.sln) file.
        ///
        ///Provide the pathname of a folder that contains a *.sln file in its topmost level, and then try to run this application again..
        /// </summary>
        public static string RootDirectoryDoesntContainSolution {
            get {
                return ResourceManager.GetString("RootDirectoryDoesntContainSolution", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The specified starting directory, &apos;{0}&apos;, does not exist.
        ///
        ///Check the value passed on the command line, and then try again..
        /// </summary>
        public static string RootDirectoryDoesntExist {
            get {
                return ResourceManager.GetString("RootDirectoryDoesntExist", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The specified directory exists on the file system and contains a Visual Studio Solution (*.sln) file..
        /// </summary>
        public static string RootDirectoryValid {
            get {
                return ResourceManager.GetString("RootDirectoryValid", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Due to an error we didn&apos;t expect, we could not perform validation on the command-line arguments supplied to this application..
        /// </summary>
        public static string UnknownCommandLineValidationFailedError {
            get {
                return ResourceManager.GetString("UnknownCommandLineValidationFailedError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Due to an error we didn&apos;t expect, we could not perform validation on the path &apos;{0}&apos; that was provided for the starting folder..
        /// </summary>
        public static string UnknownRootDirectoryValidationFailedError {
            get {
                return ResourceManager.GetString("UnknownRootDirectoryValidationFailedError", resourceCulture);
            }
        }
    }
}