//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MFR.GUI.Windows.Presenters.Properties {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "16.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("MFR.GUI.Windows.Presenters.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The text to be found cannot be blank.
        ///
        ///Type the text you want replaced, and then try again..
        /// </summary>
        public static string Error_FindWhatRequired {
            get {
                return ResourceManager.GetString("Error_FindWhatRequired", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to A profile with the name &apos;{0}&apos; already exists.
        ///
        ///You can&apos;t use the same name, even with different upper- and lower-case letters, as an existing profile..
        /// </summary>
        public static string Error_ProfileWithNameAlreadyExists {
            get {
                return ResourceManager.GetString("Error_ProfileWithNameAlreadyExists", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The text to use as replacement text cannot be blank.
        ///
        ///Type a value for this text, and then try again..
        /// </summary>
        public static string Error_ReplaceWithBlank {
            get {
                return ResourceManager.GetString("Error_ReplaceWithBlank", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Could not locate the folder &apos;{0}&apos; on the file system.
        ///
        ///Please specify a folder path of click the &apos;...&apos; button to browse for one..
        /// </summary>
        public static string Error_RootDirectoryNotFound {
            get {
                return ResourceManager.GetString("Error_RootDirectoryNotFound", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Value cannot be null or whitespace..
        /// </summary>
        public static string Error_ValueCannotBeNullOrWhiteSpace {
            get {
                return ResourceManager.GetString("Error_ValueCannotBeNullOrWhiteSpace", resourceCulture);
            }
        }
    }
}