//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MFR.Operations.Descriptions.Properties {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("MFR.Operations.Descriptions.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cleaning file(s) touched by the Replace Text in Files operation....
        /// </summary>
        public static string OperationDescription_CleanFiles {
            get {
                return ResourceManager.GetString("OperationDescription_CleanFiles", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Committing pending changes to Git....
        /// </summary>
        public static string OperationDescription_CommitPendingChanges {
            get {
                return ResourceManager.GetString("OperationDescription_CommitPendingChanges", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Committing results of operation(s) to Git....
        /// </summary>
        public static string OperationDescription_CommitResultsToGit {
            get {
                return ResourceManager.GetString("OperationDescription_CommitResultsToGit", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Loading all Visual Studio Solutions in the starting folder....
        /// </summary>
        public static string OperationDescription_LoadAllSolutionsInFolder {
            get {
                return ResourceManager.GetString("OperationDescription_LoadAllSolutionsInFolder", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Renaming files...
        /// </summary>
        public static string OperationDescription_RenameFilesInFolder {
            get {
                return ResourceManager.GetString("OperationDescription_RenameFilesInFolder", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Renaming folder(s) of Solution(s)....
        /// </summary>
        public static string OperationDescription_RenameSolutionFolders {
            get {
                return ResourceManager.GetString("OperationDescription_RenameSolutionFolders", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Renaming subfolders...
        /// </summary>
        public static string OperationDescription_RenameSubFolders {
            get {
                return ResourceManager.GetString("OperationDescription_RenameSubFolders", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Replacing text in files...
        /// </summary>
        public static string OperationDescription_ReplaceTextInFiles {
            get {
                return ResourceManager.GetString("OperationDescription_ReplaceTextInFiles", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Unloading all currenty-open Visual Studio Solutions in the starting folder....
        /// </summary>
        public static string OperationDescription_UnloadAllSolutionsInFolder {
            get {
                return ResourceManager.GetString("OperationDescription_UnloadAllSolutionsInFolder", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Getting list of files to be renamed....
        /// </summary>
        public static string OperationStartedDescription_CalculateListOfFilesToBeRenamed {
            get {
                return ResourceManager.GetString("OperationStartedDescription_CalculateListOfFilesToBeRenamed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Checking whether the folder you selected (or its subfolders) contains a Visual Studio Solution (*.sln) file....
        /// </summary>
        public static string OperationStartedDescription_CheckingWhetherChosenFolderContainsSolutions {
            get {
                return ResourceManager.GetString("OperationStartedDescription_CheckingWhetherChosenFolderContainsSolutions", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Determining which file(s) need to be cleaned....
        /// </summary>
        public static string OperationStartedDescription_CleanFiles {
            get {
                return ResourceManager.GetString("OperationStartedDescription_CleanFiles", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Closing solution containing the item(s) to be processed....
        /// </summary>
        public static string OperationStartedDescription_CloseActiveSolution {
            get {
                return ResourceManager.GetString("OperationStartedDescription_CloseActiveSolution", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Committing your existing pending change(s) to Git....
        /// </summary>
        public static string OperationStartedDescription_CommitPendingChanges {
            get {
                return ResourceManager.GetString("OperationStartedDescription_CommitPendingChanges", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Committing the results to the Git repository(ies) that exist within the directory tree....
        /// </summary>
        public static string OperationStartedDescription_CommitResultsToGit {
            get {
                return ResourceManager.GetString("OperationStartedDescription_CommitResultsToGit", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Determining whether Visual Studio is open....
        /// </summary>
        public static string OperationStartedDescription_FindVisualStudio {
            get {
                return ResourceManager.GetString("OperationStartedDescription_FindVisualStudio", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Scanning directory tree for Visual Studio Solution (*.sln) files....
        /// </summary>
        public static string OperationStartedDescription_GetListOfAllSolutionFilesInDirectoryTree {
            get {
                return ResourceManager.GetString("OperationStartedDescription_GetListOfAllSolutionFilesInDirectoryTree", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Loading user settings....
        /// </summary>
        public static string OperationStartedDescription_InitializeApplication {
            get {
                return ResourceManager.GetString("OperationStartedDescription_InitializeApplication", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Reloading the solution(s) containing the item(s) that were processed....
        /// </summary>
        public static string OperationStartedDescription_OpenActiveSolution {
            get {
                return ResourceManager.GetString("OperationStartedDescription_OpenActiveSolution", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Calculating files to be renamed...
        /// </summary>
        public static string OperationStartedDescription_RenameFilesInFolder {
            get {
                return ResourceManager.GetString("OperationStartedDescription_RenameFilesInFolder", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Getting ready to rename the folders of Solution(s) that happen to be within the directory tree....
        /// </summary>
        public static string OperationStartedDescription_RenameSolutionFolder {
            get {
                return ResourceManager.GetString("OperationStartedDescription_RenameSolutionFolder", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Calculating folders to be renamed...
        /// </summary>
        public static string OperationStartedDescription_RenameSubFolders {
            get {
                return ResourceManager.GetString("OperationStartedDescription_RenameSubFolders", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Calculating files in which to replace text...
        /// </summary>
        public static string OperationStartedDescription_ReplaceTextInFiles {
            get {
                return ResourceManager.GetString("OperationStartedDescription_ReplaceTextInFiles", resourceCulture);
            }
        }
    }
}
