//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MFR.Operations.Descriptions.Properties {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "16.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("MFR.Operations.Descriptions.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Loading all Visual Studio Solutions in the starting folder....
        /// </summary>
        internal static string OperationDescription_LoadAllSolutionsInFolder {
            get {
                return ResourceManager.GetString("OperationDescription_LoadAllSolutionsInFolder", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Renaming files...
        /// </summary>
        internal static string OperationDescription_RenameFilesInFolder {
            get {
                return ResourceManager.GetString("OperationDescription_RenameFilesInFolder", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Renaming subfolders...
        /// </summary>
        internal static string OperationDescription_RenameSubFolders {
            get {
                return ResourceManager.GetString("OperationDescription_RenameSubFolders", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Replacing text in files...
        /// </summary>
        internal static string OperationDescription_ReplaceTextInFiles {
            get {
                return ResourceManager.GetString("OperationDescription_ReplaceTextInFiles", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Unloading all currenty-open Visual Studio Solutions in the starting folder....
        /// </summary>
        internal static string OperationDescription_UnloadAllSolutionsInFolder {
            get {
                return ResourceManager.GetString("OperationDescription_UnloadAllSolutionsInFolder", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Closing solution containing the item(s) to be processed....
        /// </summary>
        internal static string OperationStartedDescription_CloseActiveSolution {
            get {
                return ResourceManager.GetString("OperationStartedDescription_CloseActiveSolution", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Determining whether Visual Studio is open....
        /// </summary>
        internal static string OperationStartedDescription_FindVisualStudio {
            get {
                return ResourceManager.GetString("OperationStartedDescription_FindVisualStudio", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Getting list of files to be renamed....
        /// </summary>
        internal static string OperationStartedDescription_GettingListOfFilesToBeRenamed {
            get {
                return ResourceManager.GetString("OperationStartedDescription_GettingListOfFilesToBeRenamed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Reloading the solution containing the item(s) that were processed....
        /// </summary>
        internal static string OperationStartedDescription_OpenActiveSolution {
            get {
                return ResourceManager.GetString("OperationStartedDescription_OpenActiveSolution", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Calculating files to be renamed...
        /// </summary>
        internal static string OperationStartedDescription_RenameFilesInFolder {
            get {
                return ResourceManager.GetString("OperationStartedDescription_RenameFilesInFolder", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Calculating folders to be renamed...
        /// </summary>
        internal static string OperationStartedDescription_RenameSubFolders {
            get {
                return ResourceManager.GetString("OperationStartedDescription_RenameSubFolders", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Calculating files in which to replace text...
        /// </summary>
        internal static string OperationStartedDescription_ReplaceTextInFiles {
            get {
                return ResourceManager.GetString("OperationStartedDescription_ReplaceTextInFiles", resourceCulture);
            }
        }
    }
}
