//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MFR.Renamers.Files.Properties {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "16.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("MFR.Renamers.Files.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to We&apos;ve noticed that you have one or more instances of Visual Studio 2019 open.
        ///
        ///It doesn&apos;t appear that the solution contaiing the project to be renamed is open in any of them.
        ///
        ///Choose File -&gt; Reopen Workspace when the selected rename operation(s) have completed if the solution is open and we missed it.
        ///
        ///Do you want to proceed with the rename operation?.
        /// </summary>
        public static string Confirm_PerformRename {
            get {
                return ResourceManager.GetString("Confirm_PerformRename", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to FileRenamer.DoProcessAll: A Visual Studio Solution file could not be located in the folder &apos;{0}&apos;.  Stopping..
        /// </summary>
        public static string Error_NoSolutionsInRootDirectory {
            get {
                return ResourceManager.GetString("Error_NoSolutionsInRootDirectory", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The operation has been aborted..
        /// </summary>
        public static string Error_OperationAborted {
            get {
                return ResourceManager.GetString("Error_OperationAborted", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Attempting to rename the folder(s) in the &apos;{0}&apos; folder that contain Visual Studio Solution (*.sln) file(s) to match the name(s) of those Solution(s)... .
        /// </summary>
        public static string StatusUpdate_AttemptingRenameSolutionFolders {
            get {
                return ResourceManager.GetString("StatusUpdate_AttemptingRenameSolutionFolders", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to *** Finished renaming solution folders in &apos;{0}&apos;..
        /// </summary>
        public static string StatusUpdate_FinishedRenamingSolutionFolders {
            get {
                return ResourceManager.GetString("StatusUpdate_FinishedRenamingSolutionFolders", resourceCulture);
            }
        }
    }
}
