//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MFR.Renamers.Files.Properties {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("MFR.Renamers.Files.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to @echo off
        ///for /f &quot;tokens=3,6,8 delims=: &quot; %%i in (&apos;handle /accepteula -p $PROCESS$ &quot;$FOLDER$&quot;&apos;) do echo Releasing %%k &amp; handle -c %%j -y -p %%i.
        /// </summary>
        public static string _release_handles {
            get {
                return ResourceManager.GetString("_release_handles", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to git add ..
        /// </summary>
        public static string Command_GitAddAll {
            get {
                return ResourceManager.GetString("Command_GitAddAll", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to git commit -m &quot;Latest updates on {1} at {0} {5}&quot; -m &quot;At {0} on {1}, the Project File Renamer was invoked to replace all occurrences of &apos;{2}&apos; with &apos;{3}&apos; in the files, folders, and names of folders of the &apos;{4}&apos; folder.&quot;.
        /// </summary>
        public static string CommitMessage_AboutToUseProjectFileRenamer {
            get {
                return ResourceManager.GetString("CommitMessage_AboutToUseProjectFileRenamer", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to git commit -m &quot;Used the Project File Renamer&quot; -m &quot;At {0} {5} on {1}, the Project File Renamer was used to replace all occurrences of &apos;{2}&apos; with &apos;{3}&apos; in the files, folders, and names of folders of the &apos;{4}&apos; folder.&quot;.
        /// </summary>
        public static string CommitMessage_UsedProjectFileRenamer {
            get {
                return ResourceManager.GetString("CommitMessage_UsedProjectFileRenamer", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to We&apos;ve noticed that you have one or more instances of Visual Studio 2019 open.
        ///
        ///It doesn&apos;t appear that the solution containing the project to be renamed is open in any of them.
        ///
        ///Choose File -&gt; Reopen Workspace when the selected rename operation(s) have completed if the solution is open and we missed it.
        ///
        ///Do you want to proceed with the rename operation?.
        /// </summary>
        public static string Confirm_PerformRename {
            get {
                return ResourceManager.GetString("Confirm_PerformRename", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The attempt to close the Solution &apos;{0}&apos; has failed..
        /// </summary>
        public static string Error_AttemptToCloseSolutionFailed {
            get {
                return ResourceManager.GetString("Error_AttemptToCloseSolutionFailed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The attempt to open the Solution &apos;{0}&apos; has failed..
        /// </summary>
        public static string Error_AttemptToOpenSolutionFailed {
            get {
                return ResourceManager.GetString("Error_AttemptToOpenSolutionFailed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to FileRenamer.DoProcessAll: A Visual Studio Solution file could not be located in the folder &apos;{0}&apos;.  Stopping..
        /// </summary>
        public static string Error_NoSolutionsInRootDirectory {
            get {
                return ResourceManager.GetString("Error_NoSolutionsInRootDirectory", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The operation has been aborted..
        /// </summary>
        public static string Error_OperationAborted {
            get {
                return ResourceManager.GetString("Error_OperationAborted", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Attempting to rename subfolders of &apos;{0}&apos;, replacing &apos;{1}&apos; with &apos;{2}&apos;....
        /// </summary>
        public static string Info_AttemptingToRenameSubFolders {
            get {
                return ResourceManager.GetString("Info_AttemptingToRenameSubFolders", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Committing your pending changes to Git....
        /// </summary>
        public static string Info_CommittingPendingChangesToGit {
            get {
                return ResourceManager.GetString("Info_CommittingPendingChangesToGit", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Committing your pending changes to Git...
        ///
        ///{0} total pending change(s) across {1} repository(ies).
        /// </summary>
        public static string Info_CommittingPendingChangesToGit_WithStats {
            get {
                return ResourceManager.GetString("Info_CommittingPendingChangesToGit_WithStats", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Committing result(s) of operation(s) to Git....
        /// </summary>
        public static string Info_CommittingResultsToGit {
            get {
                return ResourceManager.GetString("Info_CommittingResultsToGit", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Committing results of operation(s) to Git...
        ///
        ///{0} total pending change(s) across {1} repository(ies).
        /// </summary>
        public static string Info_CommittingResultsToGit_WithStats {
            get {
                return ResourceManager.GetString("Info_CommittingResultsToGit_WithStats", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Attempting to rename the folder(s) in the &apos;{0}&apos; folder that contain Visual Studio Solution (*.sln) file(s) to match the name(s) of those Solution(s)... .
        /// </summary>
        public static string StatusUpdate_AttemptingRenameSolutionFolders {
            get {
                return ResourceManager.GetString("StatusUpdate_AttemptingRenameSolutionFolders", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to *** Finished renaming solution folders in &apos;{0}&apos;..
        /// </summary>
        public static string StatusUpdate_FinishedRenamingSolutionFolders {
            get {
                return ResourceManager.GetString("StatusUpdate_FinishedRenamingSolutionFolders", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Renaming files in subfolders of &apos;{0}&apos;, replacing &apos;{1}&apos; with &apos;{2}&apos;....
        /// </summary>
        public static string StatusUpdate_RenamingFilesInFolders {
            get {
                return ResourceManager.GetString("StatusUpdate_RenamingFilesInFolders", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Failed to commit pending changes to the repository you&apos;re working in.
        ///
        ///We will still carry out the operations..
        /// </summary>
        public static string Warning_FailedCommitPendingChanges {
            get {
                return ResourceManager.GetString("Warning_FailedCommitPendingChanges", resourceCulture);
            }
        }
    }
}
