//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System.CodeDom.Compiler;
using System.ComponentModel;
using System.Diagnostics;
using System.Diagnostics.CodeAnalysis;
using System.Globalization;
using System.Resources;
using System.Runtime.CompilerServices;

namespace MassFileRenamer.Objects.Properties {
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [GeneratedCode("System.Resources.Tools.StronglyTypedResourceBuilder", "16.0.0.0")]
    [DebuggerNonUserCode()]
    [CompilerGenerated()]
    internal class Resources {
        
        private static ResourceManager resourceMan;
        
        private static CultureInfo resourceCulture;
        
        [SuppressMessage("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [EditorBrowsable(EditorBrowsableState.Advanced)]
        internal static ResourceManager ResourceManager {
            get {
                if (ReferenceEquals(resourceMan, null)) {
                    ResourceManager temp = new ResourceManager("MassFileRenamer.Objects.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [EditorBrowsable(EditorBrowsableState.Advanced)]
        internal static CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Are you sure you want to clear the Starting Folder, Find What, and Replace WIth hisotry lists?\n\nThis action cannot be undone..
        /// </summary>
        internal static string Confirm_ClearAllHistory {
            get {
                return ResourceManager.GetString("Confirm_ClearAllHistory", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to We&apos;ve noticed that you have one or more instances of Visual Studio 2019 open, but it does not appear that the solution contaiing the project to be renamed is open in any of them.
        ///
        ///Just in case we&apos;re wrong, after we&apos;ve finished the operation(s) selected, any currently-open Visual Studio solutions of which the project to be renamed is a member will have to be reloaded by choosing File -&gt; Reopen Workspace when the selected rename operation(s) have completed..
        /// </summary>
        internal static string Confirm_PerformRename {
            get {
                return ResourceManager.GetString("Confirm_PerformRename", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Renaming files...
        /// </summary>
        internal static string OperationDescription_RenameFilesInFolder {
            get {
                return ResourceManager.GetString("OperationDescription_RenameFilesInFolder", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Renaming subfolders...
        /// </summary>
        internal static string OperationDescription_RenameSubFolders {
            get {
                return ResourceManager.GetString("OperationDescription_RenameSubFolders", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Replacing text in files...
        /// </summary>
        internal static string OperationDescription_ReplaceTextInFiles {
            get {
                return ResourceManager.GetString("OperationDescription_ReplaceTextInFiles", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Closing solution containing the item(s) to be processed....
        /// </summary>
        internal static string OperationStartedDescription_CloseActiveSolution {
            get {
                return ResourceManager.GetString("OperationStartedDescription_CloseActiveSolution", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Determining whether Visual Studio is open....
        /// </summary>
        internal static string OperationStartedDescription_FindVisualStudio {
            get {
                return ResourceManager.GetString("OperationStartedDescription_FindVisualStudio", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Getting list of files to be renamed....
        /// </summary>
        internal static string OperationStartedDescription_GettingListOfFilesToBeRenamed {
            get {
                return ResourceManager.GetString("OperationStartedDescription_GettingListOfFilesToBeRenamed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Reloading the solution containing the item(s) that were processed....
        /// </summary>
        internal static string OperationStartedDescription_OpenActiveSolution {
            get {
                return ResourceManager.GetString("OperationStartedDescription_OpenActiveSolution", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Calculating files to be renamed...
        /// </summary>
        internal static string OperationStartedDescription_RenameFilesInFolder {
            get {
                return ResourceManager.GetString("OperationStartedDescription_RenameFilesInFolder", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Calculating folders to be renamed...
        /// </summary>
        internal static string OperationStartedDescription_RenameSubFolders {
            get {
                return ResourceManager.GetString("OperationStartedDescription_RenameSubFolders", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Calculating files in which to replace text...
        /// </summary>
        internal static string OperationStartedDescription_ReplaceTextInFiles {
            get {
                return ResourceManager.GetString("OperationStartedDescription_ReplaceTextInFiles", resourceCulture);
            }
        }
    }
}
